name: Build and test

on:
    push:

env:
    node_version: "16.x"

jobs:
    build-and-upload-release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout project
              uses: actions/checkout@v3
            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: "${{env.node_version}}"
                  cache: yarn
            - name: Run yarn install
              run: yarn install --immutable
            - name: Build all libraries
              run: yarn build
            - name: Run tests
              run: yarn test
